cart/urls.py
from django.urls import path
from .import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('invoices/', views.invoice_page, name='invoice'),
]

rentalapp/urls.py
from django.urls import path
from django.http import HttpResponse

from . import views

app_name = 'rentalapp'
urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),

    # Create a page that lists all products under the same category or stick with table database page
    path('rentals/', views.rentalsPage, name='rentals'),
    path('rentals/<int:id>/<slug:slug>/', views.rentalDetail, name='rental_detail'),
    path('profile/', views.profilePage, name='profile'),
    path('', views.registerPage, name='register'),
]

rentalproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('rentalapp.urls', namespace='rental')),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

class CartAddProductForm(forms.Form):
    # quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from rentalapp.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product);

    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)

    context = {'cart': cart}
    return render(request, 'cart/detail.html', context)

cart/templates/cart/detail.html
{% extends "customer/base.html" %}
{% load static %}

{% block title %}Shopping Cart{% endblock %}

{% block content %}
<div class="content">
	<div class="shopping-cart">
		<h1>Your shopping cart</h1>
		<table class="table cart">
			<thead class="table-head">
				<tr>
					<th>Image</th>
					<th>Product</th>
					<th>Brand</th>
					<th>Quantity</th>
					<th>Remove</th>
					<th>Unit Price</th>
				</tr>
			</thead>
			
			<tbody>
				{% for item in cart %}
					{% with product=item.product %}
					<tr>
						<td>
								<img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "media/img/icon-no-image.svg" %}{% endif %}" id="shopping-cart-image">
						</td>
						<td><a href="{{ product.get_absolute_url }}" class="product-url">{{ product.model }}</a></td>
						<td>{{ item.brand }}</td>
						<td>{{ item.quantity }}</td>
						<td>
							<form action="{% url "cart:cart_remove" product.id %}" method="post">
								<input type="submit" value="Remove" class="remove-btn">
								{% csrf_token %}
							</form>
						</td>
						<td class="num">${{ item.price }}</td>
					</tr>
					{% endwith %}
				{% endfor %}
				<tr class="total">
					<td colspan="4"></td>
					<td id="total-text">Total</td>
					<td class="num">${{ cart.get_total_price }}</td>
				</tr>
			</tbody>
		</table>
		<p class="text-right">
			<a href="{% url "rentalapp:rentals" %}" class="buttonlight continue-btn">Continue shopping</a>
			<a href="{% url "orders:order_create" %}" class="button checkout-btn cart-btn">Checkout</a>
		</p>
	</div>
</div>
{% endblock %}