cart/urls.py
from django.urls import path
from .import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

rentalapp/urls.py
from django.urls import path
from django.http import HttpResponse

from . import views

app_name = 'rentalapp'
urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),

    # Create a page that lists all products under the same category or stick with table database page
    path('rentals/', views.rentalsPage, name='rentals'),
    path('rentals/<int:id>/<slug:slug>/', views.rentalDetail, name='rental_detail'),
    path('profile/', views.profilePage, name='profile'),
    path('', views.registerPage, name='register'),
]

rentalproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('rentalapp.urls', namespace='rental')),
]

rentalapp/models.py
from django.contrib.auth.models import AbstractUser, AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.urls import reverse

# Create your models here.
class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, firstname, lastname, mobile, **extra_fields):
        if not email:
            raise ValueError('User must have an email')
        if not password:
            raise ValueError('User must have an password')
        if not firstname:
            raise ValueError('User must have a first name')
        if not lastname:
            raise ValueError('User must have a last name')
        if not mobile:
            raise ValueError('User must have a mobile number')

        user = self.model(
            email=self.normalize_email(email),
            firstname=firstname,
            lastname=lastname,
            mobile=mobile,
            **extra_fields
        )
        user.set_password(password) # Hashes password
        user.save(using=self._db)
        return user

    def create_user(self, email, password, firstname, lastname, mobile, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, firstname, lastname, mobile, **extra_fields)

    def create_superuser(self, email, password, firstname, lastname, mobile, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(email, password, firstname, lastname, mobile, **extra_fields)


class MyUser(AbstractBaseUser, PermissionsMixin):
    user_id = models.AutoField(primary_key=True)
    email = models.EmailField(max_length=200, unique=True)
    password = models.CharField(max_length=200)
    firstname = models.CharField(max_length=200)
    lastname = models.CharField(max_length=200)
    mobile = models.CharField(max_length=200, blank=True, null=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    hide_email = models.BooleanField(default=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['firstname', 'lastname', 'mobile']

    class Meta:
        verbose_name = 'MyUser'
        verbose_name_plural = 'MyUsers'


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('rentalapp:product_list_by_category', args=[self.slug])


class Product(models.Model):
    FUEL_TYPE_CHOICES = (
        ('Gas', 'Gas'),
        ('Electric', 'Electric'),
        ('Hybrid', 'Hybrid'),
    )
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True)
    slug = models.SlugField(max_length=200)
    model = models.CharField(max_length=200, db_index=True)
    brand = models.CharField(max_length=200, db_index=True)
    color = models.CharField(max_length=200)
    image = models.ImageField(upload_to='static/media/images/', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    capacity = models.CharField(max_length=200)
    fuel_type = models.CharField(max_length=20, choices=FUEL_TYPE_CHOICES)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('model',)
        index_together = (('id', 'slug'))

    def __str__(self):
        return self.brand + " " + self.model

    def get_absolute_url(self):
        return reverse('rentalapp:rental_detail', kwargs={'id': self.id, 'slug': self.slug})

rentalapp/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib import admin
from django.contrib.auth.models import Group
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from .models import MyUser


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confimation', widget=forms.PasswordInput)

    class Meta:
        model = MyUser
        fields = ['email', 'firstname', 'lastname']

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don\'t match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = MyUser
        fields = ('email', 'firstname', 'lastname', 'password', 'mobile')


class UserAdmin(BaseUserAdmin):
    # The forms to add and change user instances
    form = UserChangeForm
    add_form = UserCreationForm

    # The fields to be used in displaying the User model.
    # Overrides the definitions on the base UserAdmin
    # that reference specific fields on auth.User
    list_display = ('email', 'firstname', 'lastname', 'mobile', 'is_admin')
    list_filter = ('is_admin')
    fieldsets = (
        (None, {'fields': ('email', 'password')}),
        ('Personal Info', {'fields': ('mobile')}),
        ('Permissions', {'fields': ('is_admin')}),
    )
    add_fieldsets = (
        (None, {
            'classes': ('wide',),
            'fields': ('email', 'mobile', 'password1', 'password2'),
        })
    )
    # add_fieldsets is not a standard ModelAdmin attribute. UserAdmin
    # overrides get_fieldsets to use this attribute when creating a user.
    search_fields = ('email',)
    ordering = ('email',)
    filter_horizontal = ()

rentalapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import *
from .forms import UserCreationForm, UserChangeForm
from cart.forms import CartAddProductForm


# Create your views here.
def registerPage(request):
    form = UserCreationForm(request.POST or None)
    if request.method == 'POST':
        # form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # username = form.cleaned_data.get('username')
            messages.success(request, 'Account successfully created.')

            return redirect('rentalapp:login')

    context = {'form': form}
    return render(request, 'customer/accounts/register.html', context)

def loginPage(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('rentalapp:rentals')
        else:
            messages.error(request, 'Email or password is incorrect')
            return render(request, 'customer/accounts/login.html')

    context = {}
    return render(request, 'customer/accounts/login.html')

def logoutUser(request):
    # Change the availability of the products for new customers
    product_list = Product.objects.all()
    for product in product_list:
        product.available = True
        product.save()

    logout(request)
    return redirect('rentalapp:login')

def rentalsPage(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    product_list = Product.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        product_list = product.filter(category=category)

    # Pagination
    paginator = Paginator(product_list, 10) # 10 products in each page
    page_number = request.GET.get('page')
    try:
        products = paginator.get_page(page_number)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.get_page(1)
    except EmptyPage:
        # If page is out of range devliver last page of results
        products = paginator.get_page(paginator.num_pages)

    context = {'category': category, 'categories': categories, 'products': products}
    return render(request, 'customer/dashboard/rentals.html', context)

def rentalDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    cart_product_form = CartAddProductForm()

    context = {'product': product, 'cart_product_form': cart_product_form}
    return render(request, 'customer/dashboard/detail.html', context)

def profilePage(request):
    user = request.user
    form = UserChangeForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()

    context = {'user': user}
    return render(request, 'customer/dashboard/profile.html', context)

rentalapp/templates/customer/accounts/base_login.html
{% load static %}
<!DOCTYPE HTML>

<head>
	<meta charset="utf-8">
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
	<![endif]-->
	<title>{% block title %}{% endblock %}</title>
	<link href="{% static "css/login.css" %}" rel="stylesheet">

</head>

<body>
 {% block content %}
 {% endblock %}

	 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
	<!-- Include all compiled plugins (below), or include individual files as needed -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
</body>

rentalapp/templates/customer/accounts/login.html
{% extends "customer/accounts/base_login.html" %}
{% load static %}

{% block title %}Login{% endblock %}

{% block content %}
	<div id="account-card">
		<p class="card-title">User Login</p>
		<div class="login-form">
			<form method="POST" action="">
				{% csrf_token %}
				{% for message in messages %}
					<p class="bg-primary" id="messages">{{message}}</p>
				{% endfor %}
				<input type="email" name="email" placeholder="Email" class="form-control">
				<input type="password" name="password" placeholder="Password" class="form-control">
				<input type="submit" name="login" value="Login" class="account-cta">
			</form>
		</div>	
		<div class="account-redirect">
			<p class="account-info">Don't have an account? <a href="{% url 'rentalapp:register' %}">Sign Up</a></p>
		</div>
	</div>
{% endblock %}

rentalapp/templates/customer/accounts/register.html
{% extends "customer/accounts/base_login.html" %}
{% load static %}

{% block title %}Register{% endblock %}

{% block content %}
	<div id="account-card">
		<p class="card-title">New Account</p>
		<div class="login-form">
			<form method="POST" action="">
				{% csrf_token %}
				{% for field in form  %}
					{{field}}
				{% endfor %}
				<input type="submit" name="create-account" value="Create Account" class="account-cta">
			</form>
		</div>
		<div class="account-redirect">
			<p class="account-info">Already have an account? <a href="{% url 'rentalapp:login' %}">Sign In</a></p>
		</div>
	</div>

	<script>
		var form_fields = document.getElementsByTagName("input");
		form_fields[1].placeholder = "Email";
		form_fields[2].placeholder = "Firstname";
		form_fields[3].placeholder = "Lastname";
		form_fields[4].placeholder = "Password";
		form_fields[5].placeholder = "Confirm Password";

		for (var field in form_fields) {
			form_fields[fields].className += "form-control";
		}
	</script>
{% endblock %}